version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Installing Dependencies"
      - run: yarn install
      - run: CI=true yarn run build
  deploy:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "Deploying to gh-pages"
      - run: yarn run deploy
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
        requires: -build
